### ISSUE TITLE
Failed assert with multiple circles

### ISSUE THREAD

**Issue by thquinn** [seominjoon/geosolver#10]
With declarations as simple as:

```
from geosolver.solver.variable_handler import VariableHandler
from geosolver.solver.numeric_solver import NumericSolver

vh = VariableHandler()
A = vh.point('A')
B = vh.point('B')
AO = vh.circle(A)
BO = vh.circle(B)
```

I'm getting a failed assert:

```
Traceback (most recent call last):
  File "geosolve.py", line 8, in <module>
    BO = vh.circle(B)
  File ".../geosolver/solver/variable_handler.py", line 52, in circle
    r = self.number(r_name, init=init)
  File ".../geosolver/solver/variable_handler.py", line 17, in number
    assert name not in self.variables
AssertionError
```

If I comment out the second circle declaration, it works fine. I'm not having trouble with lines or anything else.

**Comment by thquinn** [comment]
To work around this, I change this line in variable_handler.py:

`r_name = "%s_r" % center.signature.id`

to

`r_name = "r_%s" % len(self.variables)`

since it seems like the former always evaluates to something like "Point_r". This prevents the newly defined radius from always having the same name.
